name: Project Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-dev:
    uses: shrey141/shared-workflows/.github/workflows/main.yml@main
    jobs:
      deploy:
        environment: dev

  deploy-prod:
    needs: deploy-dev
    uses: shrey141/shared-workflows/.github/workflows/main.yml@main
    jobs:
      deploy:
        environment: rod
