name: Project Pipeline

on:
  workflow_dispatch:

jobs:
    
  deploy-dev:
    uses: ./.github/workflows/deploy.yml
    with: 
      environment: Dev

  deploy-prod:
    needs: [deploy-dev]
    uses: ./.github/workflows/deploy.yml
    with: 
      environment: Prod
