name: Project Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-staging:
    uses: shrey141/shared-workflows/.github/workflows/main.yml@main
